services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DBURL=mongodb://mongo:27017/AB_insurance
      - MONGODB_URI=mongodb://mongo:27017/AB_insurance
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=debug
      - ENABLE_MONITORING=true
      - ENABLE_CACHE=true
      - ENABLE_RATE_LIMITING=false
      - ALLOWED_ORIGINS=http://localhost:3002,http://localhost:5173,http://127.0.0.1:5173,http://host.docker.internal:5173
      - TRANZILA_API_URL=https://secure5.tranzila.com
      - TRANZILA_SUPPLIER_ID=basheer
      - TRANZILA_TERMINAL_ID=basheer
      - TRANZILA_PASSWORD=ePWRQkDs
      - GMAIL_USER=basheerinsurance99@gmail.com
      - GMAIL_APP_PASSWORD=aobg elxm xxdr ejhc
      - EMAIL_FROM_NAME=AB Insurance Company
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    networks:
      - insurance-network
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=AB_insurance
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - insurance-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - insurance-network

volumes:
  mongo_data:
  redis_data:

networks:
  insurance-network:
    driver: bridge
